sudo: required
services:
  - docker

before_install:
  # ~
  - cd Docker/fullstack-example/client # go to build dir
  # Docker/fullstack-example/client
  - docker build -t client-tests -f ./dev.Dockerfile . # build test container

script:
  # Docker/fullstack-example/client
  - docker run -e CI=true client-tests npm run test

after_success:
  # Docker/fullstack-example/client
  - cd ..
  # Docker/fullstack-example
  # Log in to Docker
  # https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker build -t api ./api
  - docker build -t client ./client
  - docker build -t nginx ./nginx
  - docker build -t worker ./worker

  - docker tag api $DOCKER_ID/docker-cheat-sheets:fullstack-api
  - docker tag client $DOCKER_ID/docker-cheat-sheets:fullstack-client
  - docker tag nginx $DOCKER_ID/docker-cheat-sheets:fullstack-nginx
  - docker tag worker $DOCKER_ID/docker-cheat-sheets:fullstack-worker

  # Log in to Docker
  # https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
  - docker push $DOCKER_ID/docker-cheat-sheets:fullstack-api
  - docker push $DOCKER_ID/docker-cheat-sheets:fullstack-client
  - docker push $DOCKER_ID/docker-cheat-sheets:fullstack-nginx
  - docker push $DOCKER_ID/docker-cheat-sheets:fullstack-worker
deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'fullstack-example'
  env: 'FullstackExample-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-117261666017'
  bucket_path: 'fullstack-example'
  on:
    branch: master
  access_key_id:
    secure: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
