sudo: required
services:
  - docker

before_install:
  - cd Docker/dev-prod-container-example/frontend # go to build dir
  - docker build -t frontend-tests -f ci.Dockerfile . # build test container

script:
  - docker run frontend-tests npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'dev-prod-container'
  env: 'DevProdContainer-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-117261666017'
  bucket_path: 'dev-prod-container'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
