# specifies which set of objects can be created.
apiVersion: v1
# kind specifies a type of object we want to make
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client # because i've deleted my personal containers: don't want to keep them updated, Stephen's are though
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"